#
# An example .markdownlint-cli2.yaml file
#

# Disable some built-in rules
config:
  MD025: false  # Disable multiple top level headings
  MD013:
    # Number of characters
    line_length: 180
    # Number of characters for headings
    heading_line_length: 180
    # Number of characters for code blocks
    code_block_line_length: 180
    # Include code blocks
    code_blocks: true
    # Include tables
    tables: true
    # Include headings
    headings: true
    # Strict length checking
    strict: false
    # Stern length checking
    stern: false
  MD033: false  # Allow inline HTML
  no-multiple-blanks: false # Allow multiple blank lines
# Fix any fixable errors
fix: true

# Define a custom front matter pattern
#frontMatter: "<head>[^]*<\/head>"

# Ignore files referenced by .gitignore (only valid at root)
gitignore: true

# Define glob expressions to use (only valid at root)
globs:
  - "**/*.md"

ignores:
  - "CHANGELOG.md"
  - "LICENSE.md"
  - "public/**"
  - "node_modules/**"
  - "assets/**"
  - "data/**"

# Use a specific formatter (only valid at root)
outputFormatters:
  -
    - markdownlint-cli2-formatter-default

# Show found files on stdout (only valid at root)
showFound: false
noBanner: true
