name: "Theme Update"

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-theme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Update hugo modules
        run: |
          # update to latest version of all modules
          hugo mod get -u

          # update the npm dependencies
          hugo mod npm pack

          # cleanup go.sum file
          hugo mod tidy

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
          version: 10.10.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'

      - name: Install node modules
        run: pnpm install --no-frozen-lockfile

      - name: Install blog node modules
        run: pnpm add -D @fontsource/fira-code @fontsource/ibm-plex-serif

      - name: Build
        run: |
          # build the site
          hugo --minify
          # remove file generated by the build
          rm -rf public/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: develop
          title: Update theme
          commit-message: ':chore(theme): arrow_up: update to latest version'
          body: "Auto-update via GitHub Actions"
          labels: automerge
